# Generated by Django 2.2.7 on 2019-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude of Sighting')),
                ('longitude', models.FloatField(help_text='Longitude of Sighting')),
                ('squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=32)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Sighting session', max_length=2)),
                ('date', models.DateField(help_text='Sighting date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], default='adult', help_text='Age of Squirrel', max_length=16)),
            ],
        ),
    ]
