# Generated by Django 2.2.7 on 2019-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='id',
        ),
        migrations.AddField(
            model_name='sighting',
            name='approaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='chasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='climbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='eating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='foraging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='fur_color',
            field=models.CharField(choices=[('gray', 'Gray'), ('black', 'Black'), ('cinnamon', 'Cinnamon'), ('', '')], default='gray', help_text='Fur color of Squirrel', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='indifferent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='kuks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='location',
            field=models.CharField(choices=[('ground_plane', 'Ground_Plane'), ('above_ground', 'Above_Ground')], default='ground_plane', help_text='Location of Squirrel', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='moans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='other_activities',
            field=models.CharField(help_text='Other activity', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='quaas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='runs_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='specific_location',
            field=models.CharField(help_text='Specific location of Squirrel', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='tail_flags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='tail_twitches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], default='adult', help_text='Age of Squirrel', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=32, primary_key=True, serialize=False),
        ),
    ]
