# Generated by Django 2.2.7 on 2019-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191127_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', '')], default='adult', help_text='Age of Squirrel', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.CharField(choices=[('ground_plane', 'Ground_Plane'), ('above_ground', 'Above_Ground'), ('', '')], default='ground_plane', help_text='Location of Squirrel', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other activity', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific location of Squirrel', max_length=20, null=True),
        ),
    ]
