# Generated by Django 2.2.7 on 2019-12-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191127_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(help_text='Sighting date in YYYY-MM-DD format'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='squirrel_id',
            field=models.CharField(help_text="Unique Squirrel ID.\n If the ID already exist, sighting won't be add", max_length=32, primary_key=True, serialize=False),
        ),
    ]
