# Generated by Django 2.2.7 on 2019-12-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191201_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='squirrel_id',
            field=models.CharField(help_text="Unique Squirrel ID. If the ID already exist, sighting won't be add", max_length=32, primary_key=True, serialize=False),
        ),
    ]
